language: node_js
node_js:
  # wait for babel support
  # - "1.0.0"
  # - "2.0.0"
  # - "3.0.0"
  - "4.0.0"
  - "4.1.0"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
after_success:
  - npm run cov
